name: firestore_collection
description: Firestore extension with cache-first, pagination and stream builder support.
version: 0.0.2
homepage: https://github.com/furkansarihan/firestore_collection

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cloud_firestore: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: